/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salesoutlet.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.salesoutlet.controller.ManageProductController;
import lk.ijse.salesoutlet.core.dto.ProductDTO;
import lk.ijse.salesoutlet.view.util.Validator;

/**
 *
 * @author user
 */
public class ManageProduct extends javax.swing.JPanel {

    DefaultTableModel dtm = null;

    /**
     * Creates new form ManageProduct1
     */
    public ManageProduct() {

        initComponents();
        getAllProductDetails();

        tblProducts.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tblProducts.getSelectedRow() == -1) {
                    return;
                }

                String code = (String) tblProducts.getValueAt(tblProducts.getSelectedRow(), 0);
                String description = (String) tblProducts.getValueAt(tblProducts.getSelectedRow(), 1);
                double retailUPrice = (double) tblProducts.getValueAt(tblProducts.getSelectedRow(), 2);
                double wholeSaleUPrice = (double) tblProducts.getValueAt(tblProducts.getSelectedRow(), 3);
                double buyingUPrice = (double) tblProducts.getValueAt(tblProducts.getSelectedRow(), 4);
                String unitQty = (String) tblProducts.getValueAt(tblProducts.getSelectedRow(), 5);
                double qtyOnHand = (double) tblProducts.getValueAt(tblProducts.getSelectedRow(), 6);

                lblProductCode.setText(code);
                txtDescription.setText(description);
                txtRetailUPrice.setText(Double.toString(retailUPrice));
                txtWholeSaleUPrice.setText(Double.toString(wholeSaleUPrice));
                txtBuyingUPrice.setText(Double.toString(buyingUPrice));
                txtUnitQty.setText(unitQty);
                txtQtyOnHand.setText(Double.toString(qtyOnHand));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtRetailUPrice = new javax.swing.JTextField();
        txtBuyingUPrice = new javax.swing.JTextField();
        txtWholeSaleUPrice = new javax.swing.JTextField();
        txtUnitQty = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        lblProductCode = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Products");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 250, 40));

        jLabel2.setDisplayedMnemonic('d');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setLabelFor(txtDescription);
        jLabel2.setText("  Product Description");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(" Selling U/Price (Retail)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Product Code");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Qty On Hand");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("  Selling U/Price (WholeSale)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Buying U/Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Unit Qty");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 60, 30));

        txtQtyOnHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyOnHandActionPerformed(evt);
            }
        });
        jPanel2.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 290, 30));

        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 290, 30));

        txtRetailUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetailUPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtRetailUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 290, 30));

        txtBuyingUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingUPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuyingUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 290, 30));

        txtWholeSaleUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWholeSaleUPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtWholeSaleUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 290, 30));

        txtUnitQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitQtyActionPerformed(evt);
            }
        });
        jPanel2.add(txtUnitQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 290, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setDisplayedMnemonic('l');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setLabelFor(tblProducts);
        jLabel4.setText("List of Products");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, -1));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Description", "U/Price(Retail)", "U/Price(WholeSale)", "Buying U/Price", "Unit Qty", "Qty On Hand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 280));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 790, 310));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e729(0)_32.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setToolTipText("Remove product from the list");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/FontAwesome_f046(0)_32.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Update product in the list");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 40));

        btnAddNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e700(0)_32.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 190, 230));

        btnNewProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_2b(0)_48.png"))); // NOI18N
        btnNewProduct.setText("New Product");
        btnNewProduct.setToolTipText("Press this button to add product details and Press 'Add New'");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 150, 40));

        lblProductCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lblProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyOnHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyOnHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyOnHandActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        txtRetailUPrice.requestFocusInWindow();
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtRetailUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetailUPriceActionPerformed
        txtWholeSaleUPrice.requestFocusInWindow();
    }//GEN-LAST:event_txtRetailUPriceActionPerformed

    private void txtBuyingUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingUPriceActionPerformed
        txtUnitQty.requestFocusInWindow();
    }//GEN-LAST:event_txtBuyingUPriceActionPerformed

    private void txtWholeSaleUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWholeSaleUPriceActionPerformed
        txtBuyingUPrice.requestFocusInWindow();
    }//GEN-LAST:event_txtWholeSaleUPriceActionPerformed

    private void txtUnitQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitQtyActionPerformed
        txtQtyOnHand.requestFocusInWindow();
    }//GEN-LAST:event_txtUnitQtyActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        try {
            String currentProductCode = ManageProductController.getCurrentProductCode();
            clearAllTextFields();
            lblProductCode.setText(currentProductCode);
            txtDescription.requestFocusInWindow();

        } catch (Exception ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed

        String code = lblProductCode.getText();
        String description = txtDescription.getText();
        
        if (!Validator.isValidName(description)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Description");
            txtDescription.selectAll();
            txtDescription.requestFocusInWindow();
            return;                        
        }
        
        double retailUPrice = Double.parseDouble(txtRetailUPrice.getText());
        String price=txtRetailUPrice.getText();
        
        if (!Validator.isValidPrice(price)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Retail Unit Price");
            txtRetailUPrice.selectAll();
            txtRetailUPrice.requestFocusInWindow();
            return;                                    
        }
        
        double wholeSaleUPrice = Double.parseDouble(txtWholeSaleUPrice.getText());
        price=txtWholeSaleUPrice.getText();
        
        if (!Validator.isValidPrice(price)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild WholeSale Unit Price");
            txtWholeSaleUPrice.selectAll();
            txtWholeSaleUPrice.requestFocusInWindow();
            return;                                    
        }

        double buyingUPrice = Double.parseDouble(txtBuyingUPrice.getText());
        price=txtRetailUPrice.getText();
        
        if (!Validator.isValidPrice(price)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Buying Unit Price");
            txtBuyingUPrice.selectAll();
            txtBuyingUPrice.requestFocusInWindow();
            return;                                    
        }
        
        String unitQty = txtUnitQty.getText();
        
        if (!Validator.isValidUnitQty(unitQty)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Retail Unit Qty");
            txtUnitQty.selectAll();
            txtUnitQty.requestFocusInWindow();
            return;                                    
        }        
        
        double qtyOnHand = Double.parseDouble(txtQtyOnHand.getText());        
        String qty=txtQtyOnHand.getText();
        
        if (!Validator.isValidPrice(qty)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Qty");
            txtQtyOnHand.selectAll();
            txtQtyOnHand.requestFocusInWindow();
            return;                                    
        }

        ProductDTO product = new ProductDTO(code, description, retailUPrice, wholeSaleUPrice, buyingUPrice, unitQty, qtyOnHand);
        try {
            boolean isAdded = ManageProductController.addProduct(product);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Product Added Successfully");
                clearAllTextFields();
                getAllProductDetails();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add Product");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to delete this product ? ");
        if (rsp == 0) {
            String code = lblProductCode.getText();
            try {
                boolean isDeleted = ManageProductController.deleteProduct(new ProductDTO(code, null, 0, 0, 0, null, 0));
                if (isDeleted) {
                    clearAllTextFields();
                    getAllProductDetails();
                    JOptionPane.showMessageDialog(this, "Product deleted successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete this product");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to update this product ? ");
        if (rsp == 0) {
            String code = lblProductCode.getText();
            String description = txtDescription.getText();
            double retailUPrice = Double.parseDouble(txtRetailUPrice.getText());
            double wholeSaleUPrice = Double.parseDouble(txtWholeSaleUPrice.getText());
            double buyingUPrice = Double.parseDouble(txtBuyingUPrice.getText());
            String unitQty = txtUnitQty.getText();
            double qtyOnHand = Double.parseDouble(txtQtyOnHand.getText());

            ProductDTO product = new ProductDTO(code, description, retailUPrice, wholeSaleUPrice, buyingUPrice, unitQty, qtyOnHand);
            try {
                boolean isUpdated = ManageProductController.updateProduct(product);
                if (isUpdated) {
                    clearAllTextFields();
                    getAllProductDetails();
                    JOptionPane.showMessageDialog(this, "Product Updated Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Product");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductCode;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtBuyingUPrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtRetailUPrice;
    private javax.swing.JTextField txtUnitQty;
    private javax.swing.JTextField txtWholeSaleUPrice;
    // End of variables declaration//GEN-END:variables

    private void getAllProductDetails() {
        try {
            ArrayList<ProductDTO> allProducts = ManageProductController.getAllProducts();
            dtm = (DefaultTableModel) tblProducts.getModel();
            dtm.setRowCount(0);
            for (ProductDTO product : allProducts) {
                Object[] data = {
                    product.getCode(),
                    product.getDescription(),
                    product.getRetailUPrice(),
                    product.getWholeSaleUPrice(),
                    product.getBuyingUPrice(),
                    product.getUnitQty(),
                    product.getQtyOnHand()
                };
                dtm.addRow(data);
            }
            dtm.addRow(new Object[]{});

        } catch (Exception ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllTextFields() {
        lblProductCode.setText(null);
        lblProductCode.setText(null);
        txtDescription.setText(null);
        txtRetailUPrice.setText(null);
        txtWholeSaleUPrice.setText(null);
        txtBuyingUPrice.setText(null);
        txtUnitQty.setText(null);
        txtQtyOnHand.setText(null);
    }
}
