/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salesoutlet.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.salesoutlet.controller.ManageSupplierController;
import lk.ijse.salesoutlet.core.dto.SupplierDTO;
import lk.ijse.salesoutlet.view.util.Validator;

/**
 *
 * @author user
 */
public class ManageSupplier extends javax.swing.JPanel {
    
    DefaultTableModel dtm = null;

    /**
     * Creates new form ManageSupplier1
     */
    public ManageSupplier() {
        initComponents();
        getAllSupplierDetails();
        
        dtm = (DefaultTableModel) tblSupplier.getModel();
        
        tblSupplier.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if (tblSupplier.getSelectedRow() == -1) {
                    return;
                }
                
                lblSupplierID.setText((String) dtm.getValueAt(tblSupplier.getSelectedRow(), 0));
                txtSupplierName.setText((String) dtm.getValueAt(tblSupplier.getSelectedRow(), 1));
                txtAddress.setText((String) dtm.getValueAt(tblSupplier.getSelectedRow(), 2));
                txtTelephoneNo.setText((String) dtm.getValueAt(tblSupplier.getSelectedRow(), 3));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtTelephoneNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        btnNewSupplier = new javax.swing.JButton();
        lblSupplierID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Supplier ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 30));

        jLabel4.setDisplayedMnemonic('m');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setLabelFor(txtSupplierName);
        jLabel4.setText("Supplier Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("  Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 60, 30));

        jLabel2.setDisplayedMnemonic('h');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setLabelFor(txtTelephoneNo);
        jLabel2.setText("  Telephone No");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 260, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(3);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, 90));
        add(txtTelephoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 260, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e729(0)_32.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setToolTipText("Remove supplier from the list");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/FontAwesome_f046(0)_32.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Update supplier in the list");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 40));

        btnAddNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e700(0)_32.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 190, 200));

        jPanel2.setBackground(new java.awt.Color(223, 223, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setDisplayedMnemonic('l');
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setLabelFor(tblSupplier);
        jLabel6.setText(" List of Suppliers");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 152, -1));

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Address", "Telephone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 260));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 770, 290));

        btnNewSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_2b(0)_48.png"))); // NOI18N
        btnNewSupplier.setText("New Supplier");
        btnNewSupplier.setToolTipText("Press this button to add product details and Press 'Add New' button");
        btnNewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSupplierActionPerformed(evt);
            }
        });
        add(btnNewSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, 40));

        lblSupplierID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSupplierActionPerformed
        clearAllTextFields();
        
        try {
            String currentSupplierID = ManageSupplierController.getCurrentSupplierID();
            lblSupplierID.setText(currentSupplierID);
            
        } catch (Exception ex) {
            Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSupplierName.requestFocusInWindow();
    }//GEN-LAST:event_btnNewSupplierActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        String id = lblSupplierID.getText();
        
        String name = txtSupplierName.getText();
        
        if (!Validator.isValidName(name)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild name");
            txtSupplierName.selectAll();
            txtSupplierName.requestFocusInWindow();
            return;
        }
        
        String address = txtAddress.getText();
        
        if (!Validator.isValidAddress(address)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild address");
            txtAddress.selectAll();
            txtAddress.requestFocusInWindow();
            return;
        }
        
        String telNo = txtTelephoneNo.getText();
        
        if (!Validator.isValidTelNo(telNo)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Telephone Number");
            txtTelephoneNo.selectAll();
            txtTelephoneNo.requestFocusInWindow();
            return;
        }
        
        SupplierDTO supplierDTO = new SupplierDTO(id, name, address, telNo);
        try {
            boolean isAdded = ManageSupplierController.addSupplier(supplierDTO);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Supplier Added Successfully");
                clearAllTextFields();
                getAllSupplierDetails();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add Supplier due to Some Reasons");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        txtAddress.requestFocusInWindow();
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to delete this supplier ? ");
        if (rsp == 0) {
            SupplierDTO supplier = new SupplierDTO(lblSupplierID.getText(), null, null, null);
            try {
                boolean isDeleted = ManageSupplierController.deleteSupplier(supplier);
                if (isDeleted) {
                    clearAllTextFields();
                    getAllSupplierDetails();
                    JOptionPane.showMessageDialog(this, "Supplier Removed Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Remove Supplier due to Some Reasons");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String id = lblSupplierID.getText();
        
        String name = txtSupplierName.getText();
        
        if (!Validator.isValidName(name)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild name");
            txtSupplierName.selectAll();
            txtSupplierName.requestFocusInWindow();
            return;
        }
        
        String address = txtAddress.getText();
        
        if (!Validator.isValidAddress(address)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild address");
            txtAddress.selectAll();
            txtAddress.requestFocusInWindow();
            return;
        }
        
        String telNo = txtTelephoneNo.getText();
        
        if (!Validator.isValidTelNo(telNo)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Telephone Number");
            txtTelephoneNo.selectAll();
            txtTelephoneNo.requestFocusInWindow();
            return;
        }
        
        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to update this supplier ? ");
        if (rsp == 0) {
            
            try {
                boolean isUpdated = ManageSupplierController.updateSupplier(new SupplierDTO(id, name, address, telNo));
                if (isUpdated) {
                    clearAllTextFields();
                    getAllSupplierDetails();
                    JOptionPane.showMessageDialog(this, "Supplier Updated Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Supplier due to some reasons");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnNewSupplier;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtTelephoneNo;
    // End of variables declaration//GEN-END:variables

    private void getAllSupplierDetails() {
        try {
            ArrayList<SupplierDTO> allSuppliers = ManageSupplierController.getAllSuppliers();
            dtm = (DefaultTableModel) tblSupplier.getModel();
            dtm.setRowCount(0);
            for (SupplierDTO supplier : allSuppliers) {
                dtm.addRow(new Object[]{
                    supplier.getId(),
                    supplier.getName(),
                    supplier.getAddress(),
                    supplier.getTelNo()
                });
            }
            dtm.addRow(new Object[]{});
        } catch (Exception ex) {
            Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearAllTextFields() {
        lblSupplierID.setText(null);
        txtSupplierName.setText(null);
        txtAddress.setText(null);
        txtTelephoneNo.setText(null);
    }
}
