/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salesoutlet.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.jasper.Report;
import lk.ijse.salesoutlet.controller.ManageCustomerController;
import lk.ijse.salesoutlet.core.dto.CustomerDTO;
import lk.ijse.salesoutlet.view.util.Validator;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author user
 */
@Report("lk.ijse.salesoutlet.report")
public class ManageCustomer extends javax.swing.JPanel {

    private DefaultTableModel dtm = null;
    
    /**
     * Creates new form ManageCustomer1
     */
    public ManageCustomer() {
        initComponents();
        getAllCustomerDetails();

        tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tblCustomer.getSelectedRow() == -1) {
                    return;
                }

                String id = (String) dtm.getValueAt(tblCustomer.getSelectedRow(), 0);
                String name = (String) dtm.getValueAt(tblCustomer.getSelectedRow(), 1);
                String address = (String) dtm.getValueAt(tblCustomer.getSelectedRow(), 2);
                String telNo = (String) dtm.getValueAt(tblCustomer.getSelectedRow(), 3);

                lblCustomerID.setText(id);
                txtCustomerName.setText(name);
                txtAddress.setText(address);
                txtTelephoneNo.setText(telNo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtTelephoneNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnNewCustomer = new javax.swing.JButton();
        lblCustomerID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Customer ID");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        jLabel4.setDisplayedMnemonic('m');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setLabelFor(txtCustomerName);
        jLabel4.setText(" Customer Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("  Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 60, 30));

        jLabel2.setDisplayedMnemonic('h');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setLabelFor(txtTelephoneNo);
        jLabel2.setText("  Telephone No");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(3);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 260, 90));

        txtTelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNoActionPerformed(evt);
            }
        });
        add(txtTelephoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 260, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e700(0)_32.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.setToolTipText("");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_e729(0)_32.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setToolTipText("Remove customer from the list");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/FontAwesome_f046(0)_32.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Update customer in the list");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 190, 210));

        jPanel2.setBackground(new java.awt.Color(223, 223, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setDisplayedMnemonic('l');
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setLabelFor(tblCustomer);
        jLabel6.setText(" List of Customers");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 152, -1));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "Address", "Telephone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCustomer.setToolTipText("Move To");
        jScrollPane2.setViewportView(tblCustomer);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 280));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 770, 310));

        btnNewCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salesoutlet/icon/Entypo_2b(0)_48.png"))); // NOI18N
        btnNewCustomer.setText("New Customer");
        btnNewCustomer.setToolTipText("Press this button to add customer details and Press 'Add New' button");
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });
        add(btnNewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 150, 40));

        lblCustomerID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed

        String id = lblCustomerID.getText();
        String name = txtCustomerName.getText();

        if (!Validator.isValidName(name)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild name");
            txtCustomerName.selectAll();
            txtCustomerName.requestFocusInWindow();
            return;
        }

        String address = txtAddress.getText();
        
        if (!Validator.isValidAddress(address)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild address");
            txtAddress.selectAll();
            txtAddress.requestFocusInWindow();
            return;            
        }
        
        String telNo = txtTelephoneNo.getText();
        
        if (!Validator.isValidTelNo(telNo)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Telephone Number");
            txtTelephoneNo.selectAll();
            txtTelephoneNo.requestFocusInWindow();
            return;            
        }

        CustomerDTO customer = new CustomerDTO(id, name, address, telNo);
        try {
            boolean isAdded = ManageCustomerController.addCustomer(customer);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Customer Added Successfully");
                getAllCustomerDetails();
                clearAllTextFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add customer");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to delete this customer ? ");
        if (rsp == 0) {
            String id = lblCustomerID.getText();
            CustomerDTO customer = new CustomerDTO(id, null, null, null);
            try {
                boolean isDeleted = ManageCustomerController.deleteCustomer(customer);
                if (isDeleted) {
                    getAllCustomerDetails();
                    clearAllTextFields();
                    JOptionPane.showMessageDialog(this, "Customer Deleted Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete customer");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String id = lblCustomerID.getText();
        String name = txtCustomerName.getText();

        if (!Validator.isValidName(name)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild name");
            txtCustomerName.selectAll();
            txtCustomerName.requestFocusInWindow();
            return;
        }

        String address = txtAddress.getText();
        
        if (!Validator.isValidAddress(address)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild address");
            txtAddress.selectAll();
            txtAddress.requestFocusInWindow();
            return;            
        }
        
        String telNo = txtTelephoneNo.getText();
        
        if (!Validator.isValidTelNo(telNo)) {
            JOptionPane.showMessageDialog(this, "Please enter a vaild Telephone Number");
            txtTelephoneNo.selectAll();
            txtTelephoneNo.requestFocusInWindow();
            return;            
        }
        
        int rsp = JOptionPane.showConfirmDialog(this, "Do you want to update customer ? ");
        if (rsp == 0) {
            
            CustomerDTO customer = new CustomerDTO(id, name, address, telNo);
            try {
                boolean isUpdated = ManageCustomerController.updateCustomer(customer);
                if (isUpdated) {
                    JOptionPane.showMessageDialog(this, "Customer Updated Successfully");
                    clearAllTextFields();
                    getAllCustomerDetails();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Customer");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        clearAllTextFields();

        try {
            String currentCustomerID = ManageCustomerController.getCurrentCustomerID();
            lblCustomerID.setText(currentCustomerID);
            txtCustomerName.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        txtAddress.requestFocus();
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtTelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNoActionPerformed
        btnAddNew.requestFocus();
    }//GEN-LAST:event_txtTelephoneNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtTelephoneNo;
    // End of variables declaration//GEN-END:variables

    private void getAllCustomerDetails() {
        try {
            ArrayList<CustomerDTO> customers = ManageCustomerController.getAllCustomers();
            dtm = (DefaultTableModel) tblCustomer.getModel();
            dtm.setRowCount(0);
            for (CustomerDTO customer : customers) {
                Object[] data = {customer.getCustomerId(), customer.getCustomerName(), customer.getAddress(), customer.getTelNo()};
                dtm.addRow(data);
            }
            dtm.addRow(new Object[]{});
        } catch (Exception ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllTextFields() {
        lblCustomerID.setText(null);
        txtCustomerName.setText(null);
        txtAddress.setText(null);
        txtTelephoneNo.setText(null);
    }
}
