/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salesoutlet.view;

import java.awt.Dialog;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import lk.ijse.salesoutlet.controller.ManageProductController;
import lk.ijse.salesoutlet.controller.ManageSupplierController;
import lk.ijse.salesoutlet.controller.PlaceGoodReceiveNoteController;
import lk.ijse.salesoutlet.core.dto.GoodReceiveDetailDTO;
import lk.ijse.salesoutlet.core.dto.ProductDTO;
import lk.ijse.salesoutlet.core.dto.SupplierDTO;
import lk.ijse.salesoutlet.core.dto.SupplierOrderDTO;
import lk.ijse.salesoutlet.core.dto.SupplierPaymentDTO;
import lk.ijse.salesoutlet.db.DBConnection;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author user
 */
@Report("lk.ijse.salesoutlet.report")
public class PlaceGoodReceiveNote extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private String orderId;
    private double totalAmount = 0;
    private String paymentID;

    /**
     * Creates new form GoodReceiveNote1
     */
    public PlaceGoodReceiveNote() {
        initComponents();

        loadCurrentOrderID();
        loadCurrentDate();
        loadSupplierIDs();
        loadProductCodes();
        getPaymentID();
        cmbSupplierID.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        cmbSupplierID = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        lblGRNID = new javax.swing.JLabel();
        lblGRNDate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBuyingUPrice = new javax.swing.JTextField();
        txtBuyingQty = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cmbProductCode = new javax.swing.JComboBox<>();
        lblQtyOnHand = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblRetailUPrice = new javax.swing.JLabel();
        lblUnitQty = new javax.swing.JLabel();
        lblWholeSaleUPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        lblNumberOfProducts = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAddGRDetails = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Place Good Receive Note");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 320, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Good Receive Note ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("GRN Date");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, 30));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 810, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Supplier Name");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 90, 30));

        cmbSupplierID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSupplierIDItemStateChanged(evt);
            }
        });
        jPanel3.add(cmbSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText(" Supplier ID");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 30));

        lblSupplierName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSupplierName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 180, 30));

        lblGRNID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGRNID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblGRNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 30));

        lblGRNDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGRNDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblGRNDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 140, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Description");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 70, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("U/Price (WholeSale) Rs.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText(" Product Code");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" U/Price (Retail) Rs.");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Buying U/Price Rs.");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Unit Qty");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, 30));

        txtBuyingUPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtBuyingUPriceMouseReleased(evt);
            }
        });
        txtBuyingUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingUPriceActionPerformed(evt);
            }
        });
        jPanel4.add(txtBuyingUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 140, 30));

        txtBuyingQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingQtyActionPerformed(evt);
            }
        });
        jPanel4.add(txtBuyingQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 140, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Qty On Hand");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Buying Qty");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 80, 30));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 800, 10));

        cmbProductCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProductCodeItemStateChanged(evt);
            }
        });
        jPanel4.add(cmbProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 30));

        lblQtyOnHand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(lblQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 30));

        lblDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 210, 30));

        lblRetailUPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(lblRetailUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 140, 30));

        lblUnitQty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(lblUnitQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, 30));

        lblWholeSaleUPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(lblWholeSaleUPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 790, 190));
        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("List of Products");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 20));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Description", "Unit Qty", "Buying U/Price", "Buying Qty", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProducts);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 210));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 790, 240));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("No of Products");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 90, 30));

        lblNumberOfProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumberOfProducts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lblNumberOfProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 40, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Total Amount");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 120, 30));

        lblTotalAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 130, 30));

        btnRemove.setBackground(new java.awt.Color(255, 102, 102));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setText("Remove Item");
        btnRemove.setToolTipText("Remove Item From Above List");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 136, 37));

        btnAddGRDetails.setBackground(new java.awt.Color(102, 255, 51));
        btnAddGRDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddGRDetails.setText("Add GR Details");
        btnAddGRDetails.setToolTipText("Add Order,Order Details and Update ITemStock");
        btnAddGRDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGRDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddGRDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuyingUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingUPriceActionPerformed
        txtBuyingQty.requestFocus();
    }//GEN-LAST:event_txtBuyingUPriceActionPerformed

    private void txtBuyingQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingQtyActionPerformed

        dtm = (DefaultTableModel) tblProducts.getModel();

        String code = (String) cmbProductCode.getSelectedItem();
        String description = lblDescription.getText();
        String unitQty = lblUnitQty.getText();
        double buyingUPrice = Double.parseDouble(txtBuyingUPrice.getText());
        double buyingQty = Double.parseDouble(txtBuyingQty.getText());
        double amount = buyingQty * buyingUPrice;
        totalAmount += amount;

        lblTotalAmount.setText(Double.toString(totalAmount));

        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (code == dtm.getValueAt(i, 0)) {
                dtm.setValueAt((double) dtm.getValueAt(i, 4) + buyingQty, i, 4);
                dtm.setValueAt((double) dtm.getValueAt(i, 3) * (double) dtm.getValueAt(i, 4), i, 5);

                lblNumberOfProducts.setText(Integer.toString(dtm.getRowCount()));
                txtBuyingQty.setText(null);
                cmbProductCode.requestFocusInWindow();
                return;
            }
        }

        dtm.addRow(new Object[]{code, description, unitQty, buyingUPrice, buyingQty, amount});

        lblNumberOfProducts.setText(Integer.toString(dtm.getRowCount()));
        txtBuyingQty.setText(null);
        cmbProductCode.requestFocusInWindow();

    }//GEN-LAST:event_txtBuyingQtyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow = tblProducts.getSelectedRow();
        if (selectedRow != -1) {
            totalAmount -= (double) dtm.getValueAt(selectedRow, 5);

            dtm.removeRow(selectedRow);
            lblNumberOfProducts.setText(Integer.toString(dtm.getRowCount()));
            lblTotalAmount.setText(Double.toString(totalAmount));
            cmbProductCode.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddGRDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGRDetailsActionPerformed

        SupplierPaymentDTO supplierPayment = new SupplierPaymentDTO(
                paymentID,
                Double.parseDouble(lblTotalAmount.getText()),
                "NotPayed",
                null,
                null
        );

        SupplierOrderDTO order = new SupplierOrderDTO(
                lblGRNID.getText(),
                paymentID,
                (String) cmbSupplierID.getSelectedItem(),
                Integer.parseInt(lblNumberOfProducts.getText()),
                lblGRNDate.getText()
        );

        ArrayList<GoodReceiveDetailDTO> goodReceiveDetails = new ArrayList<>();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            goodReceiveDetails.add(new GoodReceiveDetailDTO(
                    lblGRNID.getText(),
                    (String) dtm.getValueAt(i, 0),
                    (double) dtm.getValueAt(i, 4),
                    (double) dtm.getValueAt(i, 3),
                    (String) dtm.getValueAt(i, 2)
            ));
        }

        try {
            boolean isOrderAdded = PlaceGoodReceiveNoteController.placeSupplierOrder(supplierPayment, order, goodReceiveDetails);
            if (isOrderAdded) {
                JOptionPane.showMessageDialog(this, "Good Receive Details Added Successfully");

                JasperUtil.init(PlaceGoodReceiveNote.class);

                JasperReportsContext ctx = JasperUtil.getReportContext();

                JasperReport compiledReport = JasperUtil.getCompiledReport("GoodReceiveNote.jasper");

                JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

                HashMap<String, Object> reportParams = new HashMap<>();
                reportParams.put("orderId", lblGRNID.getText());

                Connection connection = DBConnection.getInstance().getConnection();

                JasperPrint filledReport = fillManager.fill(compiledReport, reportParams, connection);

                IJSEJasperViewer frmViewer = new IJSEJasperViewer(filledReport);
                frmViewer.setTitle("GOOD RECEIVE NOTE");
                frmViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
                frmViewer.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Good Receive Details haven't been added Successfully due to Some Reasons");
            }
        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddGRDetailsActionPerformed

    private void cmbSupplierIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSupplierIDItemStateChanged
        String id = (String) cmbSupplierID.getSelectedItem();
        try {
            SupplierDTO searchedSupplier = ManageSupplierController.searchSupplier(new SupplierDTO(id, null, null, null));
            lblSupplierName.setText(searchedSupplier.getName());
        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSupplierIDItemStateChanged

    private void cmbProductCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProductCodeItemStateChanged
        String code = (String) cmbProductCode.getSelectedItem();
        try {
            ProductDTO searchedProduct = ManageProductController.searchProduct(new ProductDTO(code, null, 0, 0, 0, null, 0));
            lblDescription.setText(searchedProduct.getDescription());
            lblWholeSaleUPrice.setText(Double.toString(searchedProduct.getWholeSaleUPrice()));
            lblRetailUPrice.setText(Double.toString(searchedProduct.getRetailUPrice()));
            lblUnitQty.setText(searchedProduct.getUnitQty());
            lblQtyOnHand.setText(Double.toString(searchedProduct.getQtyOnHand()));
            txtBuyingUPrice.setText(Double.toString(searchedProduct.getBuyingUPrice()));

        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbProductCodeItemStateChanged

    private void txtBuyingUPriceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuyingUPriceMouseReleased
        txtBuyingUPrice.selectAll();
    }//GEN-LAST:event_txtBuyingUPriceMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGRDetails;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbProductCode;
    private javax.swing.JComboBox<String> cmbSupplierID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblGRNDate;
    private javax.swing.JLabel lblGRNID;
    private javax.swing.JLabel lblNumberOfProducts;
    private javax.swing.JLabel lblQtyOnHand;
    private javax.swing.JLabel lblRetailUPrice;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblUnitQty;
    private javax.swing.JLabel lblWholeSaleUPrice;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtBuyingQty;
    private javax.swing.JTextField txtBuyingUPrice;
    // End of variables declaration//GEN-END:variables

    private void loadCurrentOrderID() {
        try {
            String orderId = PlaceGoodReceiveNoteController.getCurrentOrderID();
            lblGRNID.setText(orderId);
        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCurrentDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String format = sdf.format(date);
        lblGRNDate.setText(format);
    }

    private void loadSupplierIDs() {
        try {
            ArrayList<SupplierDTO> allSuppliers = ManageSupplierController.getAllSuppliers();
            for (SupplierDTO supplier : allSuppliers) {
                cmbSupplierID.addItem(supplier.getId());
            }
        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadProductCodes() {
        try {
            ArrayList<ProductDTO> allProducts = ManageProductController.getAllProducts();
            for (ProductDTO product : allProducts) {
                cmbProductCode.addItem(product.getCode());
            }
        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getPaymentID() {
        try {

            paymentID = PlaceGoodReceiveNoteController.getCurrentPaymentID();

        } catch (Exception ex) {
            Logger.getLogger(PlaceGoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
